{% set name = "rapidjson" %}
# Because upstream doesn't produce releases despite active development mostly focused
# on bugfixes and compatibility with newer toolchains, we provide date based .post
# releases.
# To update, find an appropriate commit in upstream, note the commit hash and date,
# check find the checksum of the associated archive tarball (see source url below),
# and use this information to update the following three lines.
{% set version = "1.1.0.post20240409" %}
{% set commit_hash = "ab1842a2dae061284c0a62dca1cc6d5e7e37e346" %}
{% set sha256 = "39f96f17b40f7201042c9b45d6444cb7eae1b7adfb7455412a86f6140450d32d" }

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Tencent/rapidjson/archive/{{ commit_hash }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0

requirements:
  build:
    - cmake
    - make
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:

test:
  commands:
    - test -f ${PREFIX}/include/rapidjson/rapidjson.h                     # [unix]
    - test -f ${PREFIX}/lib/cmake/RapidJSON/RapidJSONConfig.cmake         # [unix]
    - test -f ${PREFIX}/lib/cmake/RapidJSON/RapidJSONConfigVersion.cmake  # [unix]
    - if exist %LIBRARY_PREFIX%\include\rapidjson\rapidjson.h (exit 0) else (exit 1)                     # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\RapidJSON\RapidJSONConfig.cmake (exit 0) else (exit 1)         # [win]
    - if exist %LIBRARY_PREFIX%\lib\cmake\RapidJSON\RapidJSONConfigVersion.cmake (exit 0) else (exit 1)  # [win]

about:
  home: https://github.com/Tencent/rapidjson
  summary: A fast JSON parser/generator for C++ with both SAX/DOM style API
  license: MIT
  license_file: license.txt
  license_family: MIT

extra:
  recipe-maintainers:
    - wesm
    - SylvainCorlay
    - JohanMabille
    - xhochy
    - zklaus
